version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - "mysql:mysql"
    networks:
      - rails-tmdb
    volumes:
      - $PWD:/usr/local/share/rails-tmdb
      - bundle:/usr/local/bundle

  mysql:
    image: "mysql:5.5"
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=rails_tmdb
    networks:
      - rails-tmdb

networks:
  rails-tmdb:

volumes:
  bundle:
